// <auto-generated />
using Assistant.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Assistant.Migrations
{
    [DbContext(typeof(AssistantContext))]
    partial class AssistantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Assistant.Models.Goods", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasColumnName("productCode")
                        .HasMaxLength(20);

                    b.Property<string>("FullName")
                        .HasColumnName("fullName")
                        .HasMaxLength(45);

                    b.Property<float?>("Price")
                        .HasColumnName("price");

                    b.Property<float?>("RetailPrice")
                        .HasColumnName("retailPrice");

                    b.Property<float?>("WholesalePrice")
                        .HasColumnName("wholesalePrice");

                    b.HasKey("ProductCode");

                    b.ToTable("goods");
                });

            modelBuilder.Entity("Assistant.Models.OrderGoods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GoodsId")
                        .HasColumnName("goodsId")
                        .HasMaxLength(20);

                    b.Property<int>("OrderId")
                        .HasColumnName("orderId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("GoodsId")
                        .HasName("goodsId_idx");

                    b.HasIndex("OrderId")
                        .HasName("orderId_idx");

                    b.ToTable("Order-Goods");
                });

            modelBuilder.Entity("Assistant.Models.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Customer")
                        .HasColumnName("customer")
                        .HasMaxLength(45);

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasMaxLength(1000);

                    b.Property<string>("Invoice")
                        .HasColumnName("invoice")
                        .HasMaxLength(45);

                    b.Property<string>("OrderPrice")
                        .HasColumnName("orderPrice")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Assistant.Models.OrderGoods", b =>
                {
                    b.HasOne("Assistant.Models.Goods", "Goods")
                        .WithMany("OrderGoods")
                        .HasForeignKey("GoodsId")
                        .HasConstraintName("goodsId");

                    b.HasOne("Assistant.Models.Orders", "Order")
                        .WithMany("OrderGoods")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("orderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
